### ISSUE TITLE
Timed out waiting for the condition on jobs/artifacts.generate

### ISSUE THREAD

**Issue by bh4rtp** [timoth-y/iot-blockchain-network#1] opened 2021-04-11 01:06 UTC
allen@dev-x1:~/helm/chainmetric-network$ ./network.sh init
Release "artifacts" does not exist. Installing it now.
NAME: artifacts
LAST DEPLOYED: Sun Apr 11 08:45:30 2021
NAMESPACE: network
STATUS: deployed
REVISION: 1
TEST SUITE: None
error: timed out waiting for the condition on jobs/artifacts.generate

My Kubenetes env:
allen@dev-x1:~$ kubectl get nodes
NAME     STATUS   ROLES                  AGE    VERSION
dev-x1   Ready    control-plane,master   2d9h   v1.20.4

**Comment by nulltea** [comment] 2021-07-08 00:45
Hey, @bh4rtp!
Sorry for leaving this one hanging for so long. It took me time to come back for this repo.
Though, it got thought some major changes since then. 
Previous repo moved to [timoth-y/chainmetric-network](https://github.com/timoth-y/chainmetric-network) and this one is now dedicated for `fabnctl` command line utility for Fabric deployment

**Comment by nulltea** [comment] 2021-07-08 00:47
Considering your issue, it is probably caused by the absence of volume provisioner, at that time [nfs](https://github.com/kubernetes-retired/external-storage/tree/master/nfs) was in use. 
I updated requirements in README to help avoid things like that in the future.

**Comment by nulltea** [comment] 2021-07-08 00:48
Don't know if you still interested in Fabric's deployments, but if so, consider checking `fabnctl` as a new tool. 
In case of new issues, please do submit them and I would try to respond quickly this time. 
I will close this one for now.

**Closed as completed by nulltea** 2021-07-08 00:48 UTC
